title: Henrique Piñeiro Monteagudo
author:
  name: Henrique Piñeiro Monteagudo
  email: "henrique.pineiro2 (at) unibo (dot) it"
  
description: > # this means to ignore newlines until "baseurl:"
  My name is Henrique Piñeiro Monteagudo, I do research in Computer Vision
  
remote_theme: jekyll/minima

show_excerpts: true # set to false to remove excerpts on the homepage

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  skin: auto
  social_links:
    - { platform: github, user_url: https://github.com/henriquepm}
    - { platform: bluesky, user_url: https://bsky.app/profile/henrique.gal}
    - { platform: linkedin, user_url: https://www.linkedin.com/in/henriqpm/}
    - { platform: google_scholar, user_url: https://scholar.google.com/citations?user=LJgeoBwAAAAJ&hl=en&oi=ao}
  
include:
    - _pages
    - _assets
